title: Our Decent Future
description: Collaborative blueprints for the future
theme: jekyll-theme-slate
baseurl: "/our-decent-future"
url: ""

# Site metadata
author: m3data
lang: en-US
timezone: UTC

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - LICENSE
  - README.md
  - .gitignore
  - vendor/
  - Gemfile
  - Gemfile.lock
  - CONTRIBUTING.md
  - docs/
  - node_modules/
  - "*.gem"
  - "*.gemspec"